version: '3'

services:
  redis-server:
    image: 'redis'

  express:
    build: './Docker'
    ports: 
      - 4000:4000
    depends_on:
      - redis-server

  react:
    build: './react-sandbox'
    ports:
      - 3000:3000
    depends_on:
      - express

